### PR TITLE
add replica count & optional node pool config (for GKE)

### PR DESCRIPTION
**Pull request by bpmct**

### CODE REVIEW

**Comment by bpmct** [comment]
:( Terraform doesn't like this despite the value being unset with null

```
"remove_default_node_pool": conflicts with enable_autopilot
```

**Comment by bpmct** [comment]
@ElliotG can I suggest we modify this example to be a non-Autopilot cluster? Autopilot is cool but makes it difficult to have feature parity with other Kubernetes examples we provide.

**Comment by ElliotG** [comment]
@bpmct  can you tell me more about this? What's the missing features?

My goal with these was not to give production-ready examples, but to use the simplest terraform possible to demonstrate that deploying Helm/Coder is easy. The more I add to it, the more it takes away from the narrative?

**Comment by ElliotG** [comment]
Closing out for now, as I want to keep the repo as simple as possible.

**Pull request closed without merging**
